# Generated by Django 2.2 on 2020-01-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('categoria', models.CharField(choices=[('Conferencia', 'Conferencia'), ('Seminario', 'Seminario'), ('Congreso', 'Congreso'), ('Curso', 'Curso')], default='Curso', max_length=2)),
                ('lugar', models.CharField(default='DEFAULT VALUE', max_length=20)),
                ('direccion', models.CharField(default='DEFAULT VALUE', max_length=20)),
                ('fechainicio', models.DateTimeField(blank=True, null=True)),
                ('fechafin', models.DateTimeField(blank=True, null=True)),
                ('tipo_evento', models.CharField(choices=[('Presencial ', 'Presencial'), ('Virtual', 'Virtual')], default='Presencial ', max_length=2)),
            ],
            options={
                'db_table': 'eventos',
            },
        ),
    ]
