# Generated by Django 2.2 on 2020-01-22 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20200122_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='fechafin',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='fechainicio',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
    ]
