# Generated by Django 2.2 on 2020-01-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_auto_20200122_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='nombre',
            field=models.CharField(default='Nombre de la Conferencia', max_length=100),
        ),
    ]
