# Generated by Django 2.2 on 2020-01-22 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_auto_20200122_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='direccion',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='lugar',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='nombre',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
