# Generated by Django 2.2 on 2020-01-22 23:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_auto_20200122_0116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventos',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='eventos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventos',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
