# Generated by Django 2.2 on 2020-01-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='categoria',
            field=models.CharField(choices=[('Conferencia', 'Conferencia'), ('Seminario', 'Seminario'), ('Congreso', 'Congreso'), ('Curso', 'Curso')], default='Curso', max_length=22),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='tipo_evento',
            field=models.CharField(choices=[('Presencial ', 'Presencial'), ('Virtual', 'Virtual')], default='Presencial ', max_length=22),
        ),
    ]
