# Generated by Django 2.2 on 2020-01-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_auto_20200122_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='direccion',
            field=models.CharField(default='Direccion', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='lugar',
            field=models.CharField(default='lugar', max_length=20),
        ),
    ]
