# Generated by Django 2.2 on 2020-01-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_auto_20200122_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='fechafin',
            field=models.CharField(default='Fecha Fin(dd-mm-aaaa)', max_length=20),
        ),
    ]
