# Generated by Django 2.2 on 2020-01-22 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_auto_20200122_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='fechafin',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='fechainicio',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
    ]
